import networkx as nx
import matplotlib.pyplot as plt

# Create an empty directed graph
G = nx.DiGraph()

# List of edges
edges = [
    ('button', 'broadcaster'),
    ('bg', 'ck'),
    ('bg', 'rq'),
    ('broadcaster', 'gn'),
    ('broadcaster', 'gb'),
    ('broadcaster', 'rb'),
    ('broadcaster', 'df'),
    ('bt', 'vd'),
    ('cc', 'vg'),
    ('ch', 'qr'),
    ('ck', 'nz'),
    ('ck', 'fv'),
    ('ck', 'rb'),
    ('ck', 'sx'),
    ('ck', 'ms'),
    ('ck', 'mt'),
    ('cs', 'qt'),
    ('df', 'hc'),
    ('df', 'lq'),
    ('dj', 'nl'),
    ('fp', 'rp'),
    ('fp', 'qt'),
    ('fr', 'ks'),
    ('fr', 'hc'),
    ('fv', 'vd'),
    ('fz', 'qt'),
    ('fz', 'zq'),
    ('gb', 'vx'),
    ('gb', 'qt'),
    ('gc', 'kb'),
    ('gc', 'pv'),
    ('gd', 'gc'),
    ('gh', 'td'),
    ('gn', 'kb'),
    ('gn', 'tn'),
    ('gq', 'hc'),
    ('gq', 'ch'),
    ('gt', 'pp'),
    ('gt', 'kb'),
    ('gv', 'kb'),
    ('hc', 'qr'),
    ('hc', 'ch'),
    ('hc', 'df'),
    ('hc', 'dj'),
    ('hc', 'cc'),
    ('hc', 'rd'),
    ('hh', 'ck'),
    ('hh', 'ms'),
    ('jb', 'fz'),
    ('jl', 'ck'),
    ('jl', 'jn'),
    ('jn', 'ck'),
    ('jn', 'nz'),
    ('kb', 'pv'),
    ('kb', 'pr'),
    ('kb', 'tn'),
    ('kb', 'nm'),
    ('kb', 'pf'),
    ('kb', 'gn'),
    ('kb', 'gd'),
    ('ks', 'lc'),
    ('ks', 'hc'),
    ('kz', 'jb'),
    ('kz', 'qt'),
    ('lc', 'hc'),
    ('lq', 'gq'),
    ('lq', 'hc'),
    ('ms', 'xz'),
    ('mt', 'sx'),
    ('nl', 'cc'),
    ('nl', 'hc'),
    ('nm', 'gt'),
    ('nz', 'hh'),
    ('pf', 'gd'),
    ('pp', 'gv'),
    ('pp', 'kb'),
    ('pr', 'vd'),
    ('ps', 'kb'),
    ('ps', 'rf'),
    ('pv', 'ps'),
    ('qr', 'dj'),
    ('qt', 'jb'),
    ('qt', 'vx'),
    ('qt', 'bt'),
    ('qt', 'gh'),
    ('qt', 'td'),
    ('qt', 'gb'),
    ('rb', 'ck'),
    ('rb', 'mt'),
    ('rd', 'vd'),
    ('rf', 'kb'),
    ('rf', 'nm'),
    ('rp', 'qt'),
    ('rp', 'gh'),
    ('rq', 'ck'),
    ('rq', 'ts'),
    ('sx', 'jl'),
    ('td', 'kz'),
    ('tn', 'pf'),
    ('ts', 'ck'),
    ('vd', 'rx'),
    ('vg', 'fr'),
    ('vg', 'hc'),
    ('vx', 'fp'),
    ('xm', 'qt'),
    ('xm', 'cs'),
    ('xz', 'ck'),
    ('xz', 'bg'),
    ('zq', 'qt'),
    ('zq', 'xm'),
    ('rx', 'Terminal')
]

# Add edges to the graph
G.add_edges_from(edges)

# Draw the graph
pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_size=500, node_color='lightblue', font_size=8, font_color='black', font_weight='bold', arrowsize=10)
plt.title("Graph Visualization")
plt.show()
